/* Pseudorandom Number Generator
 * =============================
 *
 * This module provides fast, mostly-uniformly-distributed random values as
 * generated by a seeded pseudorandom number generator.
 *
 * This file is the shared interface, accessible from both platform and
 * game code.
 * See platform/modules/rng.cc and game/modules/rng.cc for implementations
 */

#pragma once

#include "batteries_included.h"
#include "primitive_types.h"

#include <limits>

namespace rng {
    
/* Generate a random integer */
u64 integer(u64 min=std::numeric_limits<u64>::lowest(),
            u64 max=std::numeric_limits<u64>::max());

/* Generate a random floating-point number between zero and one */
f64 fraction(f64 min=0, f64 max=1);

/* Re-seed the PRNG with a particular number, rather than entropy */
void seed(u64 new_seed);

} /* namespace random */